services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Bind the project directory to /app in the container
    working_dir: /app  # Ensure the working directory is set correctly
    entrypoint: ["./bin/run_app.sh"]  # Define the entry point
