name: Build and Push Docker Image for Flask Sample application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Get short commit_id
        id: image-tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Print short commit_id
        run: echo "Short commit_id is ${{ steps.image-tag.outputs.sha_short }}"

      - name: Get the branch name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Set image tag variable
        run: |
          IMAGE_TAG="ehsanullahkhan/fastapi-helloworld:${{ env.BRANCH_NAME }}_${{ steps.image-tag.outputs.sha_short }}"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # Docker Buildx is used to generate and attach attestations and SBOM to container images,
        # enhancing the transparency and security of the build process by verifying the image's content and provenance.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ vars.DOCKER_FILE_TYPE || 'Dockerfile' }}    # Dockerfile to build to image form
          tags: ${{ env.IMAGE_TAG }}
          context: .
          push: true    # push image after build
          sbom: true
          provenance: true
          # sbom and provenance ==> Attestations in the context of building Docker images are crucial for ensuring trust, security, and integrity of the images.

      - name: Docker scout scan
        uses: docker/scout-action@v1.13.0
        with:
          image: ${{ env.IMAGE_TAG }}
          command: recommendations, quickview, cves
          only-unfixed: true    # show vulnerabilties whose fix is available
          exit-code: false      # set to true if want to fail the workflow because of vulnerabilities
